project:
  type: website

website:
  title: "Xiaochuan's page"
  navbar:
    left:
      - text: about
        href: index.qmd
        icon: person
      - text: publications
        icon: book
        href: publications.qmd
      - text: blog
        icon: cup-hot
        href: https://xiaochuany.github.io/1principle/
      - text: talks
        icon: mic
        menu: 
          - text: boundary effects in stochastic geometry
            url: https://xiaochuany.github.io/slides/
    tools:
      - href: https://www.linkedin.com/in/xiaochuan-yang-088975188/
        icon: linkedin
      - href: https://github.com/xiaochuany
        icon: github
      - href: https://www.youtube.com/@xiaochuanyang
        icon: youtube
    
    
format:
  html:
    theme: 
        light: flatly
        dark: darkly
    css: styles.css
    toc: true

execute:
  freeze: true