project:
  type: website

website:
  title: "Xiaochuan's page"
  navbar:
    left:
      - text: about
        href: index.qmd
        icon: incognito
      - text: publications
        icon: book
        href: publications.qmd
      - text: blog
        icon: cup-hot
        href: https://xiaochuany.github.io/1principle/
    tools:
      - href: https://www.linkedin.com/in/xiaochuan-yang-088975188/
        icon: linkedin
      - href: https://github.com/xiaochuany
        icon: github
    
    
format:
  html:
    theme: 
        light: flatly
        dark: darkly
    css: styles.css
    toc: true

